name: Issue Progress Notifier

on:
  issues:
    types: [opened, edited, closed, reopened]

jobs:
  notify:
    runs-on: ubuntu-latest
    environment: Issue Notifier Action
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Send notification emails
        uses: ./
        env:
          ACCESS_TOKEN: ${{ secrets.GH_TOKEN }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          SMTP_HOST: email-smtp.ap-south-1.amazonaws.com
          SMTP_PORT: 465
          SMTP_FROM: dsfx3d@gmail.com