name: Issue Progress Notifier

on:
  issues:
    types: [reopened]

jobs:
  notify:
    runs-on: ubuntu-latest
    environment: Issue Notifier Action
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Generate Email Template
        id: email_options
        uses: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Send Email
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: email-smtp.ap-south-1.amazonaws.com
          server_port: 465
          username: ${{ secrets.SMTP_USER }}
          password: ${{ secrets.SMTP_PASS }}
          subject: ${{ steps.email_options.outputs.subject }}
          body: ${{ steps.email_options.outputs.body }}
          to: ${{ steps.email_options.outputs.subscribers }}
          from: dsfx3d@gmail.com