name: Issue Progress Notifier

on:
  issues:
    types: [reopened]

jobs:
  notify:
    runs-on: ubuntu-latest
    environment: Issue Notifier Action
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Generate Email Template
        id: email_options
        uses: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Send Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: email-smtp.ap-south-1.amazonaws.com
          server_port: 465
          username: ${{ secrets.SMTP_USER }}
          password: ${{ secrets.SMTP_PASS }}
          subject: ${{ github.event.issue.title}}
          body: ${{ steps.email_options.outputs.bodyHtml }}
          html_body: ${{ steps.email_options.outputs.bodyHtml }}
          to: dsfx3d@gmail.com, yash.singh@yougov.com
          from: dsfx3d@gmail.com