name: Issue Progress Notifier

on:
  issues:
    types: [reopened, closed]

jobs:
  notify:
    runs-on: ubuntu-latest
    environment: Issue Notifier Action
    steps:
      - uses: actions/checkout@v3

      - name: Generate Email Template
        id: generate_templates
        uses: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Send Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: email-smtp.ap-south-1.amazonaws.com
          server_port: 465
          username: ${{ secrets.SMTP_USER }}
          password: ${{ secrets.SMTP_PASS }}
          subject: ${{ github.event.issue.title}}
          body: ${{ github.event.issue.body }}
          html_body: ${{ steps.generate_templates.outputs.template }}
          to: dsfx3d@gmail.com, yash.singh@yougov.com
          from: Yashodhan Singh <dsfx3d@gmail.com>