name: Issue Notification Workflow

on:
  issues:
    types: [opened, edited, closed, reopened]

jobs:
  notify:
    runs-on: ubuntu-latest
    environment: Issue Notifier Action
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Notify
        uses: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}